language: java
jdk:
  - oraclejdk8

script:
  - jdk_switcher use oraclejdk8
  - ./gradlew check
  - git submodule update
  - gradle build
  - cd cob_spec/
  - jdk_switcher use oraclejdk7
  - mvn package
  - java -jar fitnesse.jar -c "PassingTestSuite?suite&format=text"

